name: auth
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_ui_auth: ^3.0.1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  go_router: ^16.3.0
  cupertino_icons: ^1.0.8
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  cloud_firestore: ^6.0.3
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
